
from pathlib import Path
import pandas as pd

# PROJECT PATHS

PROJECT_ROOT = Path(__file__).resolve().parents[1]

DATA_DIR = PROJECT_ROOT / "data"
DATA_RAW = DATA_DIR / "raw"
DATA_PROCESSED = DATA_DIR / "processed"

OUTPUT_DIR = PROJECT_ROOT / "output"
RESULTS_DIR = OUTPUT_DIR / "results"

CLEAN_FILE = DATA_PROCESSED / "SPY_1min_clean.csv"
FEATURE_FILE = DATA_PROCESSED / "SPY_1min_features.csv"

# FEATURE PARAMETERS

LOOKBACK = 14
VOL_MULTIPLIER = 1.0

# BACKTEST PARAMETERS

INITIAL_CAPITAL = 100_000

COMMISSION_PER_SHARE = 0.0035
SLIPPAGE_PER_SHARE = 0.001

# DYNAMIC SIZING PARAMETERS

TARGET_DAILY_VOL = 0.02
MAX_LEVERAGE = 4.0

# TRAIN / TEST SPLIT

TRAIN_END = pd.Timestamp("2022-12-31")
